/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StravaDataImportRouteImport } from './routes/strava-data-import'
import { Route as MyDataRouteImport } from './routes/my-data'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StravaDataImportRoute = StravaDataImportRouteImport.update({
  id: '/strava-data-import',
  path: '/strava-data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDataRoute = MyDataRouteImport.update({
  id: '/my-data',
  path: '/my-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-data': typeof MyDataRoute
  '/strava-data-import': typeof StravaDataImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-data': typeof MyDataRoute
  '/strava-data-import': typeof StravaDataImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/my-data': typeof MyDataRoute
  '/strava-data-import': typeof StravaDataImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/my-data' | '/strava-data-import'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/my-data' | '/strava-data-import'
  id: '__root__' | '/' | '/about' | '/my-data' | '/strava-data-import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MyDataRoute: typeof MyDataRoute
  StravaDataImportRoute: typeof StravaDataImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strava-data-import': {
      id: '/strava-data-import'
      path: '/strava-data-import'
      fullPath: '/strava-data-import'
      preLoaderRoute: typeof StravaDataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-data': {
      id: '/my-data'
      path: '/my-data'
      fullPath: '/my-data'
      preLoaderRoute: typeof MyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MyDataRoute: MyDataRoute,
  StravaDataImportRoute: StravaDataImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
